// Generated by CoffeeScript 1.6.2
var UglifyMinifier, clone, sysPath, uglify,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

sysPath = require('path');

uglify = require('uglify-js');

clone = function(obj) {
  var copied, key, val;
  if ((obj == null) || typeof obj !== 'object') {
    return obj;
  }
  copied = new obj.constructor();
  for (key in obj) {
    val = obj[key];
    copied[key] = clone(val);
  }
  return copied;
};

module.exports = UglifyMinifier = (function() {
  UglifyMinifier.prototype.brunchPlugin = true;

  UglifyMinifier.prototype.type = 'javascript';

  function UglifyMinifier(config) {
    var _ref, _ref1;
    this.config = config;
    this.optimize = __bind(this.optimize, this);
    this.options = clone((_ref = this.config) != null ? (_ref1 = _ref.plugins) != null ? _ref1.uglify : void 0 : void 0);
    if (typeof this.options !== 'object') {
      this.options = {};
    }
    this.options.fromString = true;
    this.options.outSourceMap = this.config.modules.sourceMaps;
  }

  UglifyMinifier.prototype.optimize = function(data, path, callback) {
    var err, error, result;
    try {
      result = uglify.minify(data, this.options);
    } catch (_error) {
      err = _error;
      error = "JS minify failed on " + path + ": " + err;
    }
    return callback(error, result || data);
  };

  return UglifyMinifier;

})();
