// Generated by CoffeeScript 1.6.3
var UglifyMinifier, clone, sysPath, uglify;

sysPath = require('path');

uglify = require('uglify-js');

clone = function(obj) {
  var copied, key, val;
  if ((obj == null) || typeof obj !== 'object') {
    return obj;
  }
  copied = new obj.constructor();
  for (key in obj) {
    val = obj[key];
    copied[key] = clone(val);
  }
  return copied;
};

module.exports = UglifyMinifier = (function() {
  UglifyMinifier.prototype.brunchPlugin = true;

  UglifyMinifier.prototype.type = 'javascript';

  function UglifyMinifier(config) {
    var _ref, _ref1, _ref2;
    this.config = config;
    this.options = (clone((_ref = this.config) != null ? (_ref1 = _ref.plugins) != null ? _ref1.uglify : void 0 : void 0)) || {};
    this.options.fromString = true;
    this.options.sourceMaps = (_ref2 = this.config) != null ? _ref2.sourceMaps : void 0;
  }

  UglifyMinifier.prototype.optimize = function(data, path, callback) {
    var err, error, optimized, options, result;
    options = this.options;
    options.outSourceMap = options.sourceMaps ? "" + path + ".map" : void 0;
    try {
      return optimized = uglify.minify(data, options);
    } catch (_error) {
      err = _error;
      return error = "JS minify failed on " + path + ": " + err;
    } finally {
      result = optimized && options.sourceMaps ? {
        data: optimized.code,
        map: optimized.map
      } : {
        data: optimized.code
      };
      callback(error, result || data);
    }
  };

  return UglifyMinifier;

})();
