// Generated by CoffeeScript 1.6.3
var UglifyMinifier, clone, sysPath, uglify;

sysPath = require('path');

uglify = require('uglify-js');

clone = function(obj) {
  var copied, key, val;
  if ((obj == null) || typeof obj !== 'object') {
    return obj;
  }
  copied = new obj.constructor();
  for (key in obj) {
    val = obj[key];
    copied[key] = clone(val);
  }
  return copied;
};

module.exports = UglifyMinifier = (function() {
  UglifyMinifier.prototype.brunchPlugin = true;

  UglifyMinifier.prototype.type = 'javascript';

  function UglifyMinifier(config) {
    var _ref;
    this.options = (clone(config != null ? (_ref = config.plugins) != null ? _ref.uglify : void 0 : void 0)) || {};
    this.options.fromString = true;
    this.options.sourceMaps = config != null ? config.sourceMaps : void 0;
  }

  UglifyMinifier.prototype.optimize = function(data, path, callback) {
    var err, error, optimized, result;
    this.options.outSourceMap = this.options.sourceMaps ? "" + path + ".map" : void 0;
    try {
      return optimized = uglify.minify(data, this.options);
    } catch (_error) {
      err = _error;
      return error = "JS minify failed on " + path + ": " + err;
    } finally {
      if (error) {
        return callback(error);
      }
      result = optimized && this.options.sourceMaps ? {
        data: optimized.code,
        map: optimized.map
      } : {
        data: optimized.code
      };
      callback(null, result || data);
    }
  };

  return UglifyMinifier;

})();
